import datetime
from pathlib import Path
from loguru import logger


class MarkdownReporter:
    def __init__(self, output_dir="reports"):
        self.output_dir = Path(output_dir)
        self._ensure_dir()

    def _ensure_dir(self):
        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True)

    def generate(self, results):
        """
        根据扫描结果生成 Markdown 报告
        :param results: 引擎返回的任务结果列表
        """
        if not results:
            logger.info("没有发现漏洞，跳过报告生成。")
            return None

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        report_file = self.output_dir / f"scan_report_{timestamp}.md"

        with open(report_file, "w", encoding="utf-8") as f:
            # 1. 报告标题与概览
            f.write(f"# 漏洞扫描报告\n\n")
            f.write(f"- **扫描时间**: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"- **发现漏洞总数**: {len(results)}\n\n")

            # 2. 漏洞摘要表格
            f.write("## 漏洞概览\n\n")
            f.write("| 目标 URL | 漏洞名称 | 危害等级 | 详细信息 |\n")
            f.write("| :--- | :--- | :--- | :--- |\n")
            for res in results:
                f.write(
                    f"| `{res['url']}` | **{res['poc_name']}** | {self._color_severity(res['severity'])} | {res['info']} |\n")

            f.write("\n---\n\n")

            # 3. 详细详情（可选，用于扩展）
            f.write("## 🔍 详细详情\n\n")
            for i, res in enumerate(results, 1):
                f.write(f"### {i}. {res['poc_name']}\n")
                f.write(f"- **目标**: `{res['url']}`\n")
                f.write(f"- **级别**: {res['severity']}\n")
                f.write(f"- **描述**: {res['info']}\n\n")

            f.write("\n---\n*Report generated by Chaos-Dog Pulse Scanner.*")

        logger.success(f"报告已生成至: {report_file}")
        return report_file

    def _color_severity(self, severity):
        """给不同等级加个 emoji，让报告更好看"""
        mapping = {
            "Critical": "Critical",
            "High": "High",
            "Medium": "Medium",
            "Low": "Low",
            "Info": "Info"
        }
        return mapping.get(severity, severity)